In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('chennaiRestaurantData.csv')
data

,Unnamed: 0,Zomato URL,Name of Restaurant,Address,Cuisine,Price for 2,Dining Rating,Dining Rating Count
0,0,https://www.zomato.com/chennai/akbar-biriyani-...,AKBAR BIRIYANI,"Velachery Main Road, Opposite Balaji Dental Co...","['North Indian', ' Chinese', ' Arabian']",250,2.9,5
1,1,https://www.zomato.com/chennai/bobacha-1-perun...,BOBACHA,"40, SP Infocity, MGR Salai, Perungudi, Chennai","['Beverages', ' Desserts', ' Bubble Tea']",300,3.7,27
2,2,https://www.zomato.com/chennai/burger-walla-dm...,BURGER WALLA DMS FOODS,"2/183, Periyar Salai, Krishna Nagar, Palavakka...","['Fast Food', ' Street Food', ' North Indian']",200,2,4
3,3,https://www.zomato.com/chennai/chaat-adyar-adyar,CHAAT @ ADYAR,"28 B, 1st Main Road, Shastri Nagar, Adyar, Che...","['North Indian', ' Chinese', ' Street Food']",200,3.6,153
4,4,https://www.zomato.com/chennai/esait-tiffen-ce...,ESAIT TIFFEN CENTRE,"96, Gandhi Road, Tambaram, Chennai","['South Indian', ' Chinese']",200,3.6,65
...,...,...,...,...,...,...,...,...
4735,4735,https://www.zomato.com/chennai/shanas-kitchen-...,SHANA'S KITCHEN,"324, 148, First Floor, Block Z, Royapettah Hig...","['Sandwich', ' Fast Food', ' Beverages']",400,3.3,7
4736,4736,https://www.zomato.com/chennai/silicon-valley-...,SILICON VALLEY PREMIUM ICE CREAM AND KULFI,"Old 36/2, New 101, Jhony John Khan Road, Royap...","['Ice Cream', ' Beverages']",200,2,4
4737,4737,https://www.zomato.com/chennai/sri-krishna-bak...,SRI KRISHNA BAKERY AND SWEETS,"1/205, Old Mahabalipuram Road, Padur, Chennai","['Bakery', ' Fast Food']",600,3.3,16
4738,4738,https://www.zomato.com/chennai/sri-muthiah-tif...,SRI MUTHIAH TIFFIN CENTER,"12, Rajachar Street, Opposite Somasundharam Pl...","['South Indian', ' Chinese']",200,2,4
4739,4739,https://www.zomato.com/chennai/the-madras-deli...,THE MADRAS DELIGHT,"Shop 4, Nandivaram Grama Salai, Guduvancheri, ...","['Momos', ' Fast Food', ' Beverages']",250,2,4

In [3]:
data.drop(['Unnamed: 0'],axis = 1, inplace=True)

In [4]:
data.shape

(4740, 7)

In [5]:
data.isna().sum()

Zomato URL             1
Name of Restaurant     2
Address                2
Cuisine                8
Price for 2            8
Dining Rating          8
Dining Rating Count    9
dtype: int64

In [6]:
data.dropna(inplace=True)

In [7]:
data.isna().sum()

Zomato URL             0
Name of Restaurant     0
Address                0
Cuisine                0
Price for 2            0
Dining Rating          0
Dining Rating Count    0
dtype: int64

In [8]:
data

,Zomato URL,Name of Restaurant,Address,Cuisine,Price for 2,Dining Rating,Dining Rating Count
0,https://www.zomato.com/chennai/akbar-biriyani-...,AKBAR BIRIYANI,"Velachery Main Road, Opposite Balaji Dental Co...","['North Indian', ' Chinese', ' Arabian']",250,2.9,5
1,https://www.zomato.com/chennai/bobacha-1-perun...,BOBACHA,"40, SP Infocity, MGR Salai, Perungudi, Chennai","['Beverages', ' Desserts', ' Bubble Tea']",300,3.7,27
2,https://www.zomato.com/chennai/burger-walla-dm...,BURGER WALLA DMS FOODS,"2/183, Periyar Salai, Krishna Nagar, Palavakka...","['Fast Food', ' Street Food', ' North Indian']",200,2,4
3,https://www.zomato.com/chennai/chaat-adyar-adyar,CHAAT @ ADYAR,"28 B, 1st Main Road, Shastri Nagar, Adyar, Che...","['North Indian', ' Chinese', ' Street Food']",200,3.6,153
4,https://www.zomato.com/chennai/esait-tiffen-ce...,ESAIT TIFFEN CENTRE,"96, Gandhi Road, Tambaram, Chennai","['South Indian', ' Chinese']",200,3.6,65
...,...,...,...,...,...,...,...
4735,https://www.zomato.com/chennai/shanas-kitchen-...,SHANA'S KITCHEN,"324, 148, First Floor, Block Z, Royapettah Hig...","['Sandwich', ' Fast Food', ' Beverages']",400,3.3,7
4736,https://www.zomato.com/chennai/silicon-valley-...,SILICON VALLEY PREMIUM ICE CREAM AND KULFI,"Old 36/2, New 101, Jhony John Khan Road, Royap...","['Ice Cream', ' Beverages']",200,2,4
4737,https://www.zomato.com/chennai/sri-krishna-bak...,SRI KRISHNA BAKERY AND SWEETS,"1/205, Old Mahabalipuram Road, Padur, Chennai","['Bakery', ' Fast Food']",600,3.3,16
4738,https://www.zomato.com/chennai/sri-muthiah-tif...,SRI MUTHIAH TIFFIN CENTER,"12, Rajachar Street, Opposite Somasundharam Pl...","['South Indian', ' Chinese']",200,2,4
4739,https://www.zomato.com/chennai/the-madras-deli...,THE MADRAS DELIGHT,"Shop 4, Nandivaram Grama Salai, Guduvancheri, ...","['Momos', ' Fast Food', ' Beverages']",250,2,4

In [9]:
data.dtypes

Zomato URL             object
Name of Restaurant     object
Address                object
Cuisine                object
Price for 2            object
Dining Rating          object
Dining Rating Count    object
dtype: object

In [10]:
lst = data[data['Price for 2'] == ' Kodambakkam'].index.tolist()
data.drop(lst,axis = 0, inplace=True)

In [11]:
lst = data[data['Price for 2'] == ' 2nd Avenue'].index.tolist()
data.drop(lst,axis = 0, inplace=True)

In [12]:
data['Price for 2'] = data['Price for 2'].astype(int)

In [13]:
data.dtypes

Zomato URL             object
Name of Restaurant     object
Address                object
Cuisine                object
Price for 2             int32
Dining Rating          object
Dining Rating Count    object
dtype: object

In [14]:
data['Dining Rating'] = data['Dining Rating'].astype(float)

In [15]:
data['Dining Rating Count'] = data['Dining Rating Count'].astype(int)

In [16]:
data.dtypes

Zomato URL              object
Name of Restaurant      object
Address                 object
Cuisine                 object
Price for 2              int32
Dining Rating          float64
Dining Rating Count      int32
dtype: object

In [17]:
data.to_csv('zomato_cleaned.csv', index = False)

In [18]:
data

,Zomato URL,Name of Restaurant,Address,Cuisine,Price for 2,Dining Rating,Dining Rating Count
0,https://www.zomato.com/chennai/akbar-biriyani-...,AKBAR BIRIYANI,"Velachery Main Road, Opposite Balaji Dental Co...","['North Indian', ' Chinese', ' Arabian']",250,2.9,5
1,https://www.zomato.com/chennai/bobacha-1-perun...,BOBACHA,"40, SP Infocity, MGR Salai, Perungudi, Chennai","['Beverages', ' Desserts', ' Bubble Tea']",300,3.7,27
2,https://www.zomato.com/chennai/burger-walla-dm...,BURGER WALLA DMS FOODS,"2/183, Periyar Salai, Krishna Nagar, Palavakka...","['Fast Food', ' Street Food', ' North Indian']",200,2.0,4
3,https://www.zomato.com/chennai/chaat-adyar-adyar,CHAAT @ ADYAR,"28 B, 1st Main Road, Shastri Nagar, Adyar, Che...","['North Indian', ' Chinese', ' Street Food']",200,3.6,153
4,https://www.zomato.com/chennai/esait-tiffen-ce...,ESAIT TIFFEN CENTRE,"96, Gandhi Road, Tambaram, Chennai","['South Indian', ' Chinese']",200,3.6,65
...,...,...,...,...,...,...,...
4735,https://www.zomato.com/chennai/shanas-kitchen-...,SHANA'S KITCHEN,"324, 148, First Floor, Block Z, Royapettah Hig...","['Sandwich', ' Fast Food', ' Beverages']",400,3.3,7
4736,https://www.zomato.com/chennai/silicon-valley-...,SILICON VALLEY PREMIUM ICE CREAM AND KULFI,"Old 36/2, New 101, Jhony John Khan Road, Royap...","['Ice Cream', ' Beverages']",200,2.0,4
4737,https://www.zomato.com/chennai/sri-krishna-bak...,SRI KRISHNA BAKERY AND SWEETS,"1/205, Old Mahabalipuram Road, Padur, Chennai","['Bakery', ' Fast Food']",600,3.3,16
4738,https://www.zomato.com/chennai/sri-muthiah-tif...,SRI MUTHIAH TIFFIN CENTER,"12, Rajachar Street, Opposite Somasundharam Pl...","['South Indian', ' Chinese']",200,2.0,4
4739,https://www.zomato.com/chennai/the-madras-deli...,THE MADRAS DELIGHT,"Shop 4, Nandivaram Grama Salai, Guduvancheri, ...","['Momos', ' Fast Food', ' Beverages']",250,2.0,4

In [19]:
data.iloc[0,3]

"['North Indian', ' Chinese', ' Arabian']"

In [20]:
data['Cuisine'] = data.Cuisine.apply(lambda x: x[1:-1].split(', '))

In [21]:
data.loc[:,"Cuisine"][0]

["'North Indian'", "' Chinese'", "' Arabian'"]

In [22]:
lst = []
for i,val in zip(data.index,data['Cuisine'].values):
    for j in range(len(val)):
        lst.append(data.loc[i,'Cuisine'][j].replace(' ','').replace('\'', ''))

In [23]:
df = pd.DataFrame(lst)

In [24]:
df

                 0
0      NorthIndian
1          Chinese
2          Arabian
3        Beverages
4         Desserts
...            ...
12309  SouthIndian
12310      Chinese
12311        Momos
12312     FastFood
12313    Beverages

[12314 rows x 1 columns]

In [25]:
len(df[0].unique().tolist())

91

In [26]:
df[0].value_counts().index

Index(['Chinese', 'NorthIndian', 'SouthIndian', 'FastFood', 'Beverages',
       'Biryani', 'Desserts', 'Chettinad', 'StreetFood', 'Continental',
       'Bakery', 'Italian', 'Seafood', 'IceCream', 'Sandwich', 'Arabian',
       'Mughlai', 'Cafe', 'Juices', 'Pizza', 'Burger', 'BBQ', 'FingerFood',
       'Andhra', 'Kerala', 'Mithai', 'Lebanese', 'Asian', 'Rolls', 'Kebab',
       'Thai', 'Momos', 'Mexican', 'American', 'European', 'Tea',
       'HealthyFood', 'Japanese', 'Salad', 'Burmese', 'Mediterranean',
       'BarFood', 'Tamil', 'Hyderabadi', 'Malaysian', 'Bengali', 'Coffee',
       'Steak', 'Wraps', 'Sushi', 'Tibetan', 'Korean', 'SriLankan',
       'MiddleEastern', 'French', 'Rajasthani', 'Spanish', 'Singaporean',
       'Mangalorean', 'ModernIndian', 'Maharashtrian', 'Turkish', 'Naga',
       'Parsi', 'Indonesian', 'Portuguese', 'Gujarati', 'BubbleTea',
       'Moroccan', 'Vietnamese', 'RoastChicken', 'British', 'Paan', 'Greek',
       'Russian', 'Grill', 'Irish', 'DrinksOnly', 'Mishti', 'Malwani',
       'Bihari', 'Continental]', 'CharcoalChicken', 'RawMeats', 'Iranian',
       'Goan', 'Nepalese', 'Konkan', 'Tex-Mex', 'Egyptian', 'NorthEastern'],
      dtype='object')

In [31]:
df[0].value_counts()[50:]

Tibetan            7
Korean             6
SriLankan          6
MiddleEastern      5
French             5
Rajasthani         5
Spanish            4
Singaporean        4
Mangalorean        4
ModernIndian       4
Maharashtrian      3
Turkish            3
Naga               3
Parsi              2
Indonesian         2
Portuguese         2
Gujarati           2
BubbleTea          2
Moroccan           2
Vietnamese         2
RoastChicken       2
British            2
Paan               2
Greek              1
Russian            1
Grill              1
Irish              1
DrinksOnly         1
Mishti             1
Malwani            1
Bihari             1
Continental]       1
CharcoalChicken    1
RawMeats           1
Iranian            1
Goan               1
Nepalese           1
Konkan             1
Tex-Mex            1
Egyptian           1
NorthEastern       1
Name: 0, dtype: int64

In [28]:
data

,Zomato URL,Name of Restaurant,Address,Cuisine,Price for 2,Dining Rating,Dining Rating Count
0,https://www.zomato.com/chennai/akbar-biriyani-...,AKBAR BIRIYANI,"Velachery Main Road, Opposite Balaji Dental Co...","['North Indian', ' Chinese', ' Arabian']",250,2.9,5
1,https://www.zomato.com/chennai/bobacha-1-perun...,BOBACHA,"40, SP Infocity, MGR Salai, Perungudi, Chennai","['Beverages', ' Desserts', ' Bubble Tea']",300,3.7,27
2,https://www.zomato.com/chennai/burger-walla-dm...,BURGER WALLA DMS FOODS,"2/183, Periyar Salai, Krishna Nagar, Palavakka...","['Fast Food', ' Street Food', ' North Indian']",200,2.0,4
3,https://www.zomato.com/chennai/chaat-adyar-adyar,CHAAT @ ADYAR,"28 B, 1st Main Road, Shastri Nagar, Adyar, Che...","['North Indian', ' Chinese', ' Street Food']",200,3.6,153
4,https://www.zomato.com/chennai/esait-tiffen-ce...,ESAIT TIFFEN CENTRE,"96, Gandhi Road, Tambaram, Chennai","['South Indian', ' Chinese']",200,3.6,65
...,...,...,...,...,...,...,...
4735,https://www.zomato.com/chennai/shanas-kitchen-...,SHANA'S KITCHEN,"324, 148, First Floor, Block Z, Royapettah Hig...","['Sandwich', ' Fast Food', ' Beverages']",400,3.3,7
4736,https://www.zomato.com/chennai/silicon-valley-...,SILICON VALLEY PREMIUM ICE CREAM AND KULFI,"Old 36/2, New 101, Jhony John Khan Road, Royap...","['Ice Cream', ' Beverages']",200,2.0,4
4737,https://www.zomato.com/chennai/sri-krishna-bak...,SRI KRISHNA BAKERY AND SWEETS,"1/205, Old Mahabalipuram Road, Padur, Chennai","['Bakery', ' Fast Food']",600,3.3,16
4738,https://www.zomato.com/chennai/sri-muthiah-tif...,SRI MUTHIAH TIFFIN CENTER,"12, Rajachar Street, Opposite Somasundharam Pl...","['South Indian', ' Chinese']",200,2.0,4
4739,https://www.zomato.com/chennai/the-madras-deli...,THE MADRAS DELIGHT,"Shop 4, Nandivaram Grama Salai, Guduvancheri, ...","['Momos', ' Fast Food', ' Beverages']",250,2.0,4

In [29]:
for i,val in zip(data.index,data['Cuisine'].values):
    for j in range(len(val)):
        if data.loc[i,'Cuisine'][j] == 'Desserts':
            print(data.loc[i,'Cuisine'])

In [30]:
data.iloc[0,3]

["'North Indian'", "' Chinese'", "' Arabian'"]